# Generated by Django 3.0.5 on 2020-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_auto_20200505_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qst_views',
            field=models.IntegerField(default=0),
        ),
    ]
