# Generated by Django 3.0.5 on 2020-05-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0003_questions_qst_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
